version: '3.8'

services:
  web:
    build:
      context: ./
      target: dev
    deploy:
        resources:
          limits:
            cpus: '0.50'
            memory: 250M
          reservations:
            cpus: '0.25'
            memory: 20M
    volumes:
      - .:/src
    command: npm run start:dev
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*